# Generated by Django 2.1.7 on 2019-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_user', '0008_userregistrationrecord_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationrecord',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
